### ISSUE TITLE
'Search by Movie Name' followed by 'Filter Language' causes error

### ISSUE THREAD

**Issue by madebr** [subdownloader/subdownloader#23]
Steps to reproduce:
1. Set filter to 'All languages'
2. Search for an existing movie franchise
3. Set filter to 'English (US)'
4. Weird behavior, occasional crash

**Comment by sergiomb2** [comment]
yeah this also happened in tag 2.0.19 [1] , and I still can reproduce the error , the good news is since we switch to python3.
we may debug with gdb with Feature EasierPythonDebugging [2] 

[1] https://github.com/sergiomb2/subdownloader/releases/tag/v2.0.19
[2] https://lists.fedoraproject.org/archives/list/python-devel@lists.fedoraproject.org/thread/4V2VAG7LRFE54AU3EDLINENEOS4I7TG3/

**Comment by madebr** [comment]
This is fixed in 2.0.19 and master.
