### ISSUE TITLE
No testing possible on IA32 (Intel 32-bit)

### ISSUE THREAD

**Issue by andreasbaumann** [subdownloader/subdownloader#30]
### Description of problem

https://files.pythonhosted.org/ doesn't provice a Pyqt5 for Linux 32-bit.

### How reproducible

Runs tests on 32-bit intel machine.

### Actual Behavior

running test
Searching for PyQt5>=5.0.0
Reading https://pypi.org/simple/PyQt5/
No local packages or working download links found for PyQt5>=5.0.0
error: Could not find suitable distribution for Requirement.parse('PyQt5>=5.0.0')

### Version Info

  - SubDownloader Version: 2.1.0rc4
  - Python Version: 3.6.4
  - Operating System: Archlinux (https://www.archlinux32.org)

**Comment by madebr** [comment]
It looks like upstream Qt and PyQt do not support 32-bit linux anymore.

My linux distribution (Fedora) still does provide 32-bit `python-qt5` packages.
So theoretically it is possibly to run on 32-bit archs.

How about installing pyqt5 provided by your distribution and installing the other deps manually?
```
#untested
sudo dnf install python-qt5.i686
pip install --user --no-deps subdownloader
pip install --user argparse argcomplete langdetect pymediainfo sphinx-argparse docutils pytest
```

References:
http://pyqt.sourceforge.net/Docs/PyQt5/installation.html#installing-from-wheels
https://www.riverbankcomputing.com/pipermail/pyqt/2016-December/038414.html
https://rpmfind.net/linux/RPM/fedora/updates/26/i386/Packages/p/python-qt5-5.9.1-2.fc26.i686.html
https://stackoverflow.com/questions/12759761/python-pip-force-install-ignoring-dependencies

**Comment by andreasbaumann** [comment]
Ok. Ran 12 tests in 2.859s. I'll just patch out the PyQt5 >= 5.0.0 in setup.py and rely on the Archlinux
package to be installed. Closed from my point of view. Thanks.

**Comment by andreasbaumann** [comment]
Providing as reference:
https://github.com/archlinux32/packages/tree/master/community/subdownloader

**Comment by eli-schwartz** [comment]
@andreasbaumann,

Uhm. Why did you not ask @dvzrv to patch this in `prepare()` instead of `package()`?

Also: https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/subdownloader&id=fb5c9ba11352db984313d6adbb2b6ca9fb3e86be

Aside: it seems like somewhat of an unfortunate thing to add a dependency on the PyPI version of PyQt5, when that is so rarely what users will actually want. You could use https://www.python.org/dev/peps/pep-0496/ environment markers to restrict this to Windows, by the way.
